#!/bin/bash

tar Jcf conciser-ws-files.tar chrome-extension.crx chrome-extension.pem condenser_chains.json .env build-settings.json android/app/nbj-release.jks server/voice_whitelist.yaml

echo scp conciser-ws-files.tar ...

