#!/bin/bash

tar Jcf conciser-ws-files.tar \
        chrome-extension.crx \
        chrome-extension.pem \
        condenser_chains.json \
        build-settings.json \
        android/app/nbj-release.jks \
        android/play-service-account.json \
        .env

echo scp conciser-ws-files.tar ...

